### ISSUE TITLE
Table missing

### ISSUE THREAD

**Issue by infograf768** [joomla-extensions/pkg_languagepack#11]
Tried to create a List of Language packs menu item.

The table `#__languagepack_jversions` doesn't exist

**Comment by infograf768** [comment]
Its name was changed but it is still used in `/com_languagepack/models/fields/Joomlaversion.php`
```
$query = $db->getQuery(true)
				->select($db->quoteName(array('id','name'), array('value', 'text')))
				->from($db->quoteName('#__languagepack_jversions'));
```

Should be replaced I guess by `#__languagepack_applications`

**Comment by wilsonge** [comment]
Yup - good spot - thanks!
