### ISSUE TITLE
Team Coordinator email field

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/pkg_languagepack#18]
Should the coordinator email field https://github.com/joomla-extensions/pkg_languagepack/blob/master/com_languagepack/admin/models/forms/language.xml#L71-L78
not be changed to https://docs.joomla.org/Special:MyLanguage/Email_form_field_type instead of text ?

**Comment by wilsonge** [comment]
This was deliberate in that we currently space pad out the emails on the community site and use (at) Example email here: https://community.joomla.org/translations/joomla-3-translations/dutch-translation.html

So I kept it as text so we could directly add that in in the same format.

I assume in the future we can output the raw email and use the Joomla built in email cloak plugin but that will need to be a second round of improvements - it's not something I have ready now.

**Comment by conconnl** [comment]
The community site hasn't been fully maintained for years, different things there are the old way 😂 
That said.... 
On most of the sites (like CJO) we have the Email Protector plugin running from RegularLabs which makes sure it's protected for spam bots. I would no matter what have that running on the Downloads site as well. 

Why not do the small change and make it correct from the start?
Especially thinking about the IDP connection it should be like that.

**Comment by wilsonge** [comment]
OK If you can setup the email protector plugin on the sandbox site I'm happy to fix it up to work properly

**Comment by conconnl** [comment]
Done

**Comment by conconnl** [comment]
Could we still look at this?
