### ISSUE TITLE
Team Coordinator website field

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/pkg_languagepack#19]
Should the coordinator website field https://github.com/joomla-extensions/pkg_languagepack/blob/master/com_languagepack/admin/models/forms/language.xml#L79-L86
not be changed to https://docs.joomla.org/Special:MyLanguage/URL_form_field_type instead of text ?

**Comment by wilsonge** [comment]
yes it should

**Comment by wilsonge** [comment]
Fixed in https://github.com/joomla-extensions/pkg_languagepack/commit/7faddb15b1c98009412c007135d7e331cf5f5182
