### ISSUE TITLE
[Imagery] Badge

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/pkg_languagepack#23]
One of the texts is mentioning the use of a badge "Joomla Translation Teams may use the Joomla Translation Team badge".
Where is this badge located, can't find it on CJO or even on the official page within TM https://tm.joomla.org/conditional-use-logos.html

**Comment by infograf768** [comment]
The badge is displayed here
https://community.joomla.org/images/archive/translationteams/joomla_transteam_sm.png

![joomla_transteam_sm](https://user-images.githubusercontent.com/869724/102004655-fab7fe80-3d12-11eb-9c5b-c8dc4bfdf3d6.png)


https://community.joomla.org/translations/joomla-3-translations.html

It was designed for lang community sites with specific TT providing core translations.
It was conceived as a way to attach these communities to Joomla and prevent false accreditations.

It's use is officially described here: https://community.joomla.org/translations/joomla-project-translation-and-localization-policy.html#badge-use-policy

> Joomla! Translation Team Agreement
> Terms and Conditions for acceptance as a Joomla Translation Team
> [...]
> 
> Badge Use Policy
> 
> Joomla Translation Teams may use the Joomla Translation Team badge on their Web sites under certain conditions. These are:
> 
>     The site is non commercial.
>     The site complies with all relevant Open Source Matters policies.
>     The badge must be linked to community.joomla.org/translations.html.
>     The site makes it clear that it is not an official site of the Joomla Project.
>     The badge is not altered in any way.
> 


It looks that it is not used a lot these days. But here are some example of its use
http://joomla.mk/
https://www.joomlacommunity.nl/nieuws/versies/joomla-1526-vrijgegeven
https://www.joomlafarsi.com/
https://www.joomla.pl/
https://joomlaportal.ru/

**Comment by conconnl** [comment]
Do you still want to provide an official badge to translators, coordinators and teams?
If so we need to work with TM to put it on the official page and link from the download page information to make sure people can find it.

What are your thoughts about this part?

**Comment by infograf768** [comment]
The badge was conceived **only for communities websites providing core lang packs though a Translation Team**, not for any other use (single translator, coordinator, team). Unless you decide to modify the Translation policy, I personally don't mind if you add it to wherever you see fit. We always have considered the Translation Policy page to be the official page for that.

**Comment by conconnl** [comment]
I have discussed it with Trademark, conclusion is: 
* We create a new version in line with the current ones.
* We publish it on the trademark website like the other ones. https://tm.joomla.org/conditional-use-logos.html
* We will update the Translation and Localization policy to reflect this change, which is now located on: https://docs.joomla.org/Translation_of_Language_Packs

**Comment by conconnl** [comment]
![joomla_translation_team_horizontal](https://user-images.githubusercontent.com/11913918/102414536-ff243600-3ff6-11eb-8206-33ddf0a5c36c.png)
![joomla_translation_team_square](https://user-images.githubusercontent.com/11913918/102414539-ffbccc80-3ff6-11eb-8e9d-1b92b396199b.png)

**Comment by conconnl** [comment]
The badge is now on the trademark website: https://tm.joomla.org/conditional-use-logos.html#joomla-translation-teams
The docs site badge policy part will be updated
