### ISSUE TITLE
[Textual] - Link in new functionalities slider broken

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/pkg_languagepack#24]
One of the sliders: https://github.com/joomla-extensions/pkg_languagepack/blob/master/com_languagepack/site/language/en-GB/en-GB.com_languagepack.ini#L61-L62

Hold a link too: https://docs.joomla.org/Language_Switcher_Tutorial_for_Joomla_1.6
Which mentions a redirect, only that one results in a 404

**Comment by infograf768** [comment]
`COM_LANGUAGE_PACK_JOOMLA_VERSION_3_0_EXTRA_INFO_4_BODY="<p><a href=\"https://docs.joomla.org/International_Enhancements_for_Version_1.6\">3.x brings a lot of new functionalities in Joomla!</a><br> <a href=\"https://docs.joomla.org/Language_Switcher_Tutorial_for_Joomla_1.6\">including a simple multilanguage site implementation</a>.</p>"`

should be modified.

The most comprehensive doc is

https://docs.joomla.org/J3.x:Setup_a_Multilingual_Site

**Comment by conconnl** [comment]
Should we change it too:


`
COM_LANGUAGE_PACK_JOOMLA_VERSION_3_0_EXTRA_INFO_4_BODY="<p><a href=\"https://docs.joomla.org/J3.x:Setup_a_Multilingual_Site\">Setup a multilingual site easily</a>.</p>"
`

**Comment by infograf768** [comment]
Looks fine. You may want to have that phrase looked at by a native English speaker.
Could rather be for example : "Easily set up a multilingual site."

**Comment by conconnl** [comment]
Added the change.
@wilsonge and @JazParkyn can check the sentences when we are finished with all changes as native speakers.
