### ISSUE TITLE
[Sorting] - The languages are not sorted Alphabetically 

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/pkg_languagepack#29]
I think it’s better to sort the languages alphabetical in the list of every application. 
I’m just guessing, but probably a small update here.

https://github.com/joomla-extensions/pkg_languagepack/blob/e57a0ae1b87bd9e9b737f43438c8946866070030/com_languagepack/site/models/application.php#L48-L56

**Comment by wilsonge** [comment]
You'd be right :)
