### ISSUE TITLE
Add lock functionality to application

### ISSUE THREAD

**Issue by wilsonge** [joomla-extensions/pkg_languagepack#30]
To stop uploads of new packs to deprecated applications

**Comment by conconnl** [comment]
My suggestion would be to follow the same principal as the implemented state switch.
So, add a column "new_releases" in the DB with a 1 or 0, which means:
1 new releases can be created in a version.

If it is zero, we don't need this button:
https://github.com/joomla-extensions/pkg_languagepack/blob/master/com_languagepack/site/views/application/tmpl/default.php#L111-L113

**Comment by wilsonge** [comment]
Should be fixed in https://github.com/joomla-extensions/pkg_languagepack/commit/d10ecbc6e3ad2974fd62b04dea10ce4ebeaeea87
