### ISSUE TITLE
Stick to facts

### ISSUE THREAD

**Issue by brianteeman** [joomla-extensions/pkg_languagepack#31]
COM_LANGUAGE_PACK_APPLICATIONS_INFO="Currently supporting %d languages, Joomla! speaks more languages than any other content management system. If your site users speak one language and your administrators another, you can customize your language settings to serve their needs—even on an individual user basis. Whether you speak French, Japanese, or Farsi, Joomla! speaks your language."

Drupal claims more than 100 languages [source](https://www.drupal.org/features/multilingual)
Wordpress claims even more [source](https://translate.wordpress.org/stats/)

**Comment by conconnl** [comment]
The sentence has been changed too:
"Joomla! speaks more languages than any other content management system. If your site users speak one language and your administrators another, you can customize your language settings to serve their needs—even on an individual user basis. Whether you speak French, Japanese, or Farsi, Joomla! speaks your language."

The number of supported languages are added to the specific version and automatically calculated based on the languages added.
https://github.com/joomla-extensions/pkg_languagepack/blob/master/com_languagepack/site/language/en-GB/en-GB.com_languagepack.ini#L39-L43

**Comment by brianteeman** [comment]
I was referring to

> Joomla! speaks more languages than any other content management system.

This is not true as I indicated

**Comment by conconnl** [comment]
Please suggest something better.
This is coming from the translation site which states this for many years.
https://community.joomla.org/translations/

**Comment by brianteeman** [comment]
And its been wrong for all that time ;)

"Joomla! speaks your language, whether you speak French, Japanese, or Farsi. If your site users speak one language and your administrators another, you can customize the language settings to serve their needs - even on an individual user basis. "

**Comment by brianteeman** [comment]
Thanks
