### ISSUE TITLE
Add Language Code to new package view

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/pkg_languagepack#40]
Add the language code behind the language name.
So we get (Albanian sq-AL)

![image](https://user-images.githubusercontent.com/11913918/106353454-f78cc800-62ea-11eb-8aef-64b4ee48f17e.png)

**Comment by wilsonge** [comment]
Yes - but what’s the use case? People uploading their packs shouldn’t need to care what their language code is? Or is this because the multi-German (etc) cases?

**Comment by conconnl** [comment]
I came too this point when uploading the 1.5 packages. I had to check another page to select the correct file. Seeing the language code make this easier and not all uploaders need it but it doesn’t bring any additional confusion when it’s visible.
