### ISSUE TITLE
Ordering ARS Category selector in backend

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/pkg_languagepack#49]
@wilsonge or @Llewellynvdm 
Can you please change the code in this file, so the lists of ARS Categories are alphabetical, now it's just the order added to the database.
https://github.com/joomla-extensions/pkg_languagepack/blob/master/com_languagepack/admin/models/fields/arscategory.php

<img width="501" alt="image" src="https://user-images.githubusercontent.com/11913918/120903551-0099f700-c647-11eb-89e0-ae9e3f33e2a5.png">

**Comment by wilsonge** [comment]
https://github.com/joomla-extensions/pkg_languagepack/commit/2c478a486dadcb7d299d24845f52a3cc86b2ae5f

**Comment by conconnl** [comment]
Thanks
