### ISSUE TITLE
Bug when pressing Submit before upload has finished

### ISSUE THREAD

**Issue by rbuelund** [joomla-extensions/pkg_languagepack#51]
If one selects a language pack and immediately after that presses the submit buttn, then after a fex seconds when the upload has finished you get an error page. If you instead wait for the filename to appear in the browse box, and after that press the Submit button, then it works.
You should not be able to activate the submit button at all, before the upload has finished.

**Comment by wilsonge** [comment]
I've marked the field as required. Hopefully this should do the job! Let me know when you next upload a pack please :)
