### ISSUE TITLE
Coordinator mail displayed broken when using CJO address

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/pkg_languagepack#53]
The moment a coordinator has a @community.joomla.org mail address the frontend display acts strangely.
The CDN plugin somehow changes the address into the CDN address.
Probably because the field is a text one and not an email type.

On every refresh it's at a different point.
<img width="647" alt="image" src="https://user-images.githubusercontent.com/11913918/122123446-449eb000-ce2e-11eb-83e2-a99c49884362.png">

**Comment by wilsonge** [comment]
The rendering of the field has nothing to do with its type. Although I changed that to email last week. We’ll need to debug the cdn stuff I guess. Is it just the template that has that code in?

**Comment by conconnl** [comment]
For what I have seen (don't know why).
The whole site is in the CDN.
At least the configuration is:


Server: | File Path: | Orginal: | CDN: | CNAME:
-- | -- | -- | -- | --
joomla-org | /home/djorg/public_html | https://downloads.joomla.org | https://downloadscdn.joomla.org | joomladownloads.rochencdn.com

**Comment by conconnl** [comment]
Fix by Harald with a small tweak to use Joomla mail cloak and with that being able to disabled a third party plugin
