### ISSUE TITLE
Need to be able to delete wrong package!

### ISSUE THREAD

**Issue by rbuelund** [joomla-extensions/pkg_languagepack#61]
As language coordinator of the Danish language I need to be able to delete a faulty uploaded package here; https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-danish/4-0-0-rc5-2 - I believe the need for deleting a package could come later on too..

**Comment by syntaxerror** [comment]
I agree it could be usefull, both to be able to delete and edit.

**Comment by HLeithner** [comment]
That's not planned for the moment, if you need to delete a language pack please contact the Language Team Leader.
