### ISSUE TITLE
Replace instructions Language String with article load

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/pkg_languagepack#7]
I hope I explain correctly 😄 

File: https://github.com/joomla-extensions/pkg_languagepack/blob/master/com_languagepack/site/views/applications/tmpl/default.php
Line 35: 	<p><?php echo Text::_('COM_LANGUAGE_PACK_HOW_TO_INSTALL'); ?></p>

Can you replace this line with a configurable article load option?
In the configuration part of the component add a field where you can select the article to load.
Then load it on this place.

I checked the current pages on CJO, it's a reasonable amount of questions and answers with links. This is not really maintainable in a language string.

**Comment by wilsonge** [comment]
Just to confirm this is the one you asked me to put in with https://github.com/joomla-extensions/pkg_languagepack/issues/5 ?

**Comment by conconnl** [comment]
I mean this line now:
<p><?php echo Text::_('COM_LANGUAGE_PACK_HOW_TO_INSTALL'); ?></p>

It loads a language string to hold the information for the CJO site, but that contains articles.
If this position can load an article, it's much easier to create and maintain.

**Comment by wilsonge** [comment]
<img width="911" alt="Screenshot 2020-06-21 at 16 18 03" src="https://user-images.githubusercontent.com/1986000/85228317-bdfdf100-b3da-11ea-888f-a7a8da18310a.png">

Can make it an article. But there's no real information on the CJO site https://community.joomla.org/translations.html

**Comment by conconnl** [comment]
Just think about the future. 
If we can select an article in the config, we can extend the information as well in the future. 
If we don’t and we want to extend info it can be a blocking point for that simple action.

**Comment by infograf768** [comment]
We don't need at least 1.x and 1.5

**Comment by conconnl** [comment]
Not needed anymore
