### ISSUE TITLE
When creating new releases we should be able to select and add more info

### ISSUE THREAD

**Issue by syntaxerror** [joomla-extensions/pkg_languagepack#76]
When we're creating new releases we should be able to select and add more info, like we could at JoomlaCode.

T.ex. we should be able to add notes about the releases, what was changed, and such things.

Also selecting the maturity, if it's stable, beta or whatever. Now every release is listed as stable with a fixed note.

![2021-08-24 12 47 43 downloads joomla org](https://user-images.githubusercontent.com/858132/130595862-241ed455-52ae-4417-8bc0-26c47067aef7.png)
![2021-08-24 12 48 21 downloads joomla org](https://user-images.githubusercontent.com/858132/130595873-a2bc30f3-0289-49a5-b5d3-477cf87fa63e.png)

**Comment by HLeithner** [comment]
That's not planned, since at some point in time we would like to (semi-)automatically create releases (in)directly from crowdin. I'm closing this for now but you can always open it again.
